using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wpf2Html5.Converter
{
    public enum OutputDisposition
    {
        unspecified,
        input,
        output
    };

    /// <summary>Represents output generated by the converter.</summary>
    public class ConverterOutput
    {
        #region Private

        private Stream _ms;

        #endregion

        #region Public Properties

        public string Name { get; set; }

        public long FileSize { get { return _ms.Length; } }

        public string OriginalPath { get; set; }

        public OutputDisposition Disposition { get; set; }

        /// <summary>
        /// True if this resource shall be included in the output.
        /// </summary>
        public bool IsIncluded { get; set; }

        #endregion

        #region Construction

        public ConverterOutput(Stream stream)
        {
            _ms = new MemoryStream();
            stream.CopyTo(_ms);
        }

        #endregion

        #region Public Methods

        public Stream GetStream()
        {
            _ms.Position = 0;
            var result = new MemoryStream();
            _ms.CopyTo(result);
            result.Position = 0;
            return result;
        }

        #endregion
    }
}
